npmRegistryServer: "https://registry.npmjs.org/"

packageExtensions:
  react-scroll-manager@*:
    dependencies:
      debug: "*"
  recharts@*:
    dependencies:
      events: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
