npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  "react-scroll-manager@*":
    dependencies:
      "debug": "*"
  "recharts@*":
    dependencies:
      "events": "*"
